<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-20T14:21:02 IST" name="Default suite" finished-at="2025-06-20T14:22:52 IST" duration-ms="110179">
    <groups>
    </groups>
    <test started-at="2025-06-20T14:21:02 IST" name="Default test" finished-at="2025-06-20T14:22:52 IST" duration-ms="110179">
      <class name="Demo.Testing">
        <test-method is-config="true" signature="setUpDriver()[pri:0, instance:Demo.Testing@b86de0d]" started-at="2025-06-20T14:21:01 IST" name="setUpDriver" finished-at="2025-06-20T14:21:02 IST" duration-ms="1271" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpDriver -->
        <test-method is-config="true" signature="setupData()[pri:0, instance:Demo.Testing@b86de0d]" started-at="2025-06-20T14:21:02 IST" name="setupData" finished-at="2025-06-20T14:21:02 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupData -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Demo.Testing@b86de0d]" started-at="2025-06-20T14:21:02 IST" name="launchApplication" finished-at="2025-06-20T14:21:03 IST" duration-ms="653" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="InvoiceWithNoDeduction(java.util.HashMap)[pri:0, instance:Demo.Testing@b86de0d]" started-at="2025-06-20T14:21:03 IST" name="InvoiceWithNoDeduction" data-provider="RDVInvoiceData" finished-at="2025-06-20T14:22:49 IST" duration-ms="105836" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userName=4350143, mofRequestNo=0, taxMethod=احتساب على الوزارة 15%}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Amount validation failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Amount validation failed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at Demo.Testing.InvoiceWithNoDeduction(Testing.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvoiceWithNoDeduction -->
        <test-method is-config="true" signature="logout()[pri:0, instance:Demo.Testing@b86de0d]" started-at="2025-06-20T14:22:49 IST" name="logout" finished-at="2025-06-20T14:22:52 IST" duration-ms="3438" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:Demo.Testing@b86de0d]" started-at="2025-06-20T14:22:52 IST" name="quitBrowser" finished-at="2025-06-20T14:22:52 IST" duration-ms="195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- Demo.Testing -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
